config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :analytics do
    collection do
      delete 'destroy_all', to: 'analytics#destroy_all'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  post "save_log" => "analytics#save_log", as: :save_log

  post "search" => "articles#search", as: :search

  # get "search" => "articles#search", as: :search

  root "articles#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/analytic.rb
class Analytic
  include Mongoid::Document
  include Mongoid::Timestamps
  field :ip, type: String
  field :searchQuery, type: String
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps
  field :id, type: String
  field :article_name, type: String
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  before_action :set_analytic, only: %i[ show edit update destroy ]

  # GET /analytics or /analytics.json
  def index
    ip = ipinfo()
    if ip 
      @analytic_trend = Analytic.where(ip: ip).group_by(&:searchQuery).map{|k,v| [k, v.count]}.sort_by{|k,v| v}.reverse
    end
  end

  def ipinfo
    
    access_token = 'd5d41ac8302a60'
    handler = IPinfo::create(access_token)
    details = handler.details()
    city = details.loc + details.timezone + details.latitude + details.longitude
    puts details.all
    return city
  end

  # GET /searchQueryanalytics/1 or /analytics/1.json
  def show
  end

  # GET /analytics/new
  def new
    @analytic = Analytic.new
  end

  # GET /analytics/1/edit
  def edit
  end

  # POST /analytics or /analytics.json
  def create
    @analytic = Analytic.new(analytic_params)

    respond_to do |format|
      if @analytic.save
        format.html { redirect_to analytic_url(@analytic), notice: "Analytic was successfully created." }
        format.json { render :show, status: :created, location: @analytic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @analytic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analytics/1 or /analytics/1.json
  def update
    respond_to do |format|
      if @analytic.update(analytic_params)
        format.html { redirect_to analytic_url(@analytic), notice: "Analytic was successfully updated." }
        format.json { render :show, status: :ok, location: @analytic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @analytic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analytics/1 or /analytics/1.json
  def destroy
    @analytic.destroy!

    respond_to do |format|
      format.html { redirect_to analytics_url, notice: "Analytic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def save_log
    ip = ipinfo()
    if ip
      @analytic = Analytic.new({ip: ip, searchQuery: params[:searchQuery]})
      @analytic.save
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analytic
      @analytic = Analytic.find(params[:id])
    end

    

    # Only allow a list of trusted parameters through.
    def analytic_params
      params.require(:analytic).permit(:ip, :searchQuery)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  def search
    @query = params[:query]
    @articles = Article.where(article_name: /^#{@query}/i) if @query.present?
    render json: @articles
  end

  # GET /articles or /articles.json
  def index
    @articles = []
    # @articles = @articles.where(article_name: /^#{@query}/i) if @query.present?
  end

  

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:id, :article_name)
    end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/analytics/_analytic.html.erb
<div id="<%= dom_id analytic %>">
  <p>
    <%# <strong>Ip: </strong> %>
    <%# <%= analytic.ip %> 
  </p>

  <p>
    <strong>Searchquery:</strong>
    <%= analytic.searchQuery %>
  </p>

</div>

app/views/analytics/_form.html.erb
<%= form_with(model: analytic) do |form| %>
  <% if analytic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(analytic.errors.count, "error") %> prohibited this analytic from being saved:</h2>

      <ul>
        <% analytic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ip, style: "display: block" %>
    <%= form.text_field :ip %>
  </div>

  <div>
    <%= form.label :searchQuery, style: "display: block" %>
    <%= form.text_field :searchQuery %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/analytics/edit.html.erb
<h1>Editing analytic</h1>

<%= render "form", analytic: @analytic %>

<br>

<div>
  <%= link_to "Show this analytic", @analytic %> |
  <%= link_to "Back to analytics", analytics_path %>
</div>

app/views/analytics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Analytics</h1>
<div id="analytics" style="display: flex; gap: 30px; flex-wrap: wrap;">
  <% @analytic_trend.each_with_index do |analytic, index| %>
    <div style="background: lightblue; padding: 4px 10px; border-radius: 10px;">
      <strong style="font-size: 18px;"><%= analytic[0] %></strong>
      <p>Count: <%= analytic[1] %></p> 
      </p>
    </div>
  <% end %>
</div>

<div>
  <%= link_to "Search Articles", root_path, data: { turbo: "false" } %>
</div>

app/views/analytics/new.html.erb
<div style="display: flex; width: 100%; justify-content: space-between;">
  <div>
    <h1>Search Articles</h1>
    <input id="search" type="text" placeholder="Search Articles" />
    <br>
  </div>
  <div>
    <%= link_to "Analytics", analytics_path %>
  </div>
</div>

app/views/analytics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @analytic %>

<div>
  <%= link_to "Edit this analytic", edit_analytic_path(@analytic) %> |
  <%= link_to "Back to analytics", analytics_path %>

  <%= button_to "Destroy this analytic", @analytic, method: :delete %>
</div>

app/views/articles/_article.html.erb
<div style="background-color: lightgray; cursor: pointer;" id="<%= dom_id article %>">
  <p style="padding: 6px; border-radius: 12px;">
    <%# <strong>Article name:</strong> %>
    <%= article.article_name %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.text_field :id %>
  </div>

  <div>
    <%= form.label :article_name, style: "display: block" %>
    <%= form.text_field :article_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_results.html.erb
<% @records.each do |result| %>
  <div class="result">
    <%= result.article_name %> <!-- Adjust this based on your actual column name -->
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<div style="display: flex; width: 100%; justify-content: space-between;">
  <div>
    <input style="border-radius: 6px; padding: 6px 8px; border: 1px solid lightgray; outline: none;" id="search" type="text" placeholder="Search Articles" />
    <br>
  </div>
  <div>
    <%= link_to "Analytics", analytics_path %>
  </div>
</div>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Analytics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'script' %>
    <%= turbo_include_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>